// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.mjs";
import * as Guard from "./Guard.res.mjs";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_string from "@rescript/runtime/lib/es6/Js_string.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function assertionEqual(operator, expected, actual) {
  Test.assertion(undefined, operator, (a, b) => a === b, actual, expected);
}

function assertionTrue(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === "mutation", actual, "mutation");
}

function assertionFalse(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === "finish", actual, "finish");
}

function assertionIsTrue(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === true, actual, true);
}

function assertionIsFalse(operator, actual) {
  Test.assertion(undefined, operator, (_a, b) => b === false, actual, false);
}

function assertionNullableEqual(operator, actual, expected) {
  if (actual == null) {
    return Test.assertion(undefined, operator, (_a, _b) => false, 0, expected);
  } else {
    return assertionEqual(operator, expected, actual);
  }
}

function argsDict(d) {
  return Js_dict.fromArray([[
      "filePath",
      d.filePath
    ]]);
}

function commandDict(d) {
  return Js_dict.fromArray([[
      "command",
      d.command
    ]]);
}

function grepArgsDict(pattern, path) {
  return Js_dict.fromArray([
    [
      "pattern",
      pattern
    ],
    [
      "path",
      path
    ]
  ]);
}

Test.test("THREAT MATRIX: requirements.txt => allowed (mutation)", () => assertionTrue("requirements.txt", Guard.classify({
  tool: "write",
  args: Primitive_option.some(argsDict({
    filePath: "requirements.txt"
  }))
}, Guard.makePolicyDefault())));

Test.test("THREAT MATRIX: CMakeLists.txt => allowed (mutation)", () => assertionTrue("CMakeLists.txt", Guard.classify({
  tool: "write",
  args: Primitive_option.some(argsDict({
    filePath: "CMakeLists.txt"
  }))
}, Guard.makePolicyDefault())));

Test.test("THREAT MATRIX: README.md => allowed (mutation)", () => assertionTrue("README.md", Guard.classify({
  tool: "write",
  args: Primitive_option.some(argsDict({
    filePath: "README.md"
  }))
}, Guard.makePolicyDefault())));

Test.test("THREAT MATRIX: .ts source files => allowed (mutation, not self_script)", () => {
  assertionTrue("app.ts", Guard.classify({
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "src/app.ts"
    }))
  }, Guard.makePolicyDefault()));
  assertionTrue("index.ts", Guard.classify({
    tool: "edit",
    args: Primitive_option.some(argsDict({
      filePath: "src/index.ts"
    }))
  }, Guard.makePolicyDefault()));
});

Test.test("THREAT MATRIX: README.sh DEFAULT (no blockScriptWrites) => NOT self_script (mutation allowed)", () => {
  let p = Guard.makePolicyDefault();
  let kind = Guard.classify({
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "README.sh"
    }))
  }, p);
  assertionEqual("README.sh default", kind, "mutation");
});

Test.test("THREAT MATRIX: README.sh with blockScriptWrites:true => self_script (blocked)", () => {
  let p = Guard.makePolicyWithBlockScriptWrites(true);
  let kind = Guard.classify({
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "README.sh"
    }))
  }, p);
  assertionEqual("README.sh opt-in", kind, "self_script");
});

Test.test("THREAT MATRIX: bash heredoc (cat <<EOF) => self_script (blocked)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsTrue("heredoc", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "cat <<EOF\nhello\nEOF"
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash redirect to script (> foo.sh) => self_script (blocked)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsTrue("redirect-sh", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "echo hello > foo.sh"
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash redirect to script (>> foo.mjs) => self_script (blocked)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsTrue("redirect-mjs", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "echo hello >> foo.mjs"
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash 'node -e' => self_script (blocked)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsTrue("node -e", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "node -e 'console.log(1)'"
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash 'python3 -c' => self_script (blocked)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsTrue("python3 -c", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "python3 -c 'print(1)'"
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash 'deno eval' => self_script (blocked)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsTrue("deno eval", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "deno eval 'console.log(1)'"
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash 'bun -e' => self_script (blocked)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsTrue("bun -e", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "bun -e \"console.log('hi')\""
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash 'npm test' => NOT self_script (allowed)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsFalse("npm test", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "npm test"
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash 'tsc --noEmit' => NOT self_script (allowed)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsFalse("tsc --noEmit", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "tsc --noEmit"
    }))
  }, p));
});

Test.test("THREAT MATRIX: bash 'cat > foo.txt' (non-script) => NOT self_script (allowed)", () => {
  let p = Guard.makePolicyDefault();
  assertionIsFalse("cat-txt", Guard.isSelfScript({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "cat > foo.txt"
    }))
  }, p));
});

Test.test("isSelfScript: deliverablePath=build.sh + write build.sh => false (exempt)", () => {
  let p = Guard.makePolicyWithDeliverablePath("build.sh");
  assertionIsFalse("deliverablePath exempt", Guard.isSelfScript({
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "build.sh"
    }))
  }, p));
});

Test.test("isSelfScript: deliverablePath=build.sh + write other.sh (blockScriptWrites:true) => true", () => {
  let p = Guard.makePolicyWithDeliverablePathAndBlockScript("build.sh", true);
  assertionIsTrue("other.sh blocked", Guard.isSelfScript({
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "other.sh"
    }))
  }, p));
});

Test.test("isSelfScript: deliverableIsScript:true + write build.sh => false (intent wins)", () => {
  let p = Guard.makePolicyWithDeliverableIsScript(true);
  assertionIsFalse("deliverableIsScript", Guard.isSelfScript({
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "build.sh"
    }))
  }, p));
});

Test.test("classify: finish tools => finish", () => {
  let p = Guard.makePolicyDefault();
  assertionEqual("finish", Guard.classify({
    tool: "finish"
  }, p), "finish");
  assertionEqual("return", Guard.classify({
    tool: "return"
  }, p), "finish");
  assertionEqual("task_complete", Guard.classify({
    tool: "task_complete"
  }, p), "finish");
});

Test.test("classify: read tools => read", () => {
  let p = Guard.makePolicyDefault();
  assertionEqual("grep", Guard.classify({
    tool: "grep"
  }, p), "read");
  assertionEqual("read", Guard.classify({
    tool: "read"
  }, p), "read");
  assertionEqual("glob", Guard.classify({
    tool: "glob"
  }, p), "read");
  assertionEqual("ls", Guard.classify({
    tool: "ls"
  }, p), "read");
});

Test.test("classify: mutation tools => mutation", () => {
  let p = Guard.makePolicyDefault();
  assertionEqual("write", Guard.classify({
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "x.txt"
    }))
  }, p), "mutation");
  assertionEqual("edit", Guard.classify({
    tool: "edit",
    args: Primitive_option.some(argsDict({
      filePath: "x.txt"
    }))
  }, p), "mutation");
  assertionEqual("patch", Guard.classify({
    tool: "patch",
    args: Primitive_option.some(argsDict({
      filePath: "x.txt"
    }))
  }, p), "mutation");
  assertionEqual("bash", Guard.classify({
    tool: "bash",
    args: Primitive_option.some(commandDict({
      command: "npm test"
    }))
  }, p), "mutation");
  assertionEqual("multiedit", Guard.classify({
    tool: "multiedit",
    args: Primitive_option.some(argsDict({
      filePath: "x.txt"
    }))
  }, p), "mutation");
});

Test.test("classify: unknown tool => other", () => {
  let p = Guard.makePolicyDefault();
  assertionEqual("foo", Guard.classify({
    tool: "foo"
  }, p), "other");
});

Test.test("evaluateGuards: finish always allowed even when budget exhausted", () => {
  let p = Guard.makePolicyWithDefaults({
    budget: 8,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  s.toolCallCount = 8;
  s.budget = 8;
  let d = Guard.evaluateGuards(s, {
    tool: "finish"
  }, p);
  assertionIsTrue("finish allowed", d.allow);
});

Test.test("evaluateGuards: finish allowed even when deliverableSignal set + not executed", () => {
  let p = Guard.makePolicyWithDefaults({
    budget: 8,
    deliverableSignal: "write:output.txt"
  });
  let s = Guard.newGuardState(p);
  s.deliverableExecuted = false;
  let d = Guard.evaluateGuards(s, {
    tool: "return"
  }, p);
  assertionIsTrue("finish allowed with signal", d.allow);
});

Test.test("evaluateGuards: self_script => deny with anti_self_script guard", () => {
  let p = Guard.makePolicyWithDefaults({
    deliverableSignal: "write:output.txt",
    blockScriptWrites: Primitive_option.some(true)
  });
  let s = Guard.newGuardState(p);
  let d = Guard.evaluateGuards(s, {
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "run.sh"
    }))
  }, p);
  assertionIsFalse("self_script denied", d.allow);
  assertionEqual("anti_self_script", d.guard, "anti_self_script");
});

Test.test("evaluateGuards: self_script with blockSelfScript:false => treated as mutation (allowed)", () => {
  let p = Guard.makePolicyWithDefaults({
    blockSelfScript: false,
    deliverableSignal: null,
    blockScriptWrites: Primitive_option.some(true)
  });
  let s = Guard.newGuardState(p);
  let d = Guard.evaluateGuards(s, {
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "run.sh"
    }))
  }, p);
  assertionIsTrue("blockSelfScript=false", d.allow);
});

Test.test("evaluateGuards: toolCallCount=budget => iteration_cap denied", () => {
  let p = Guard.makePolicyWithDefaults({
    budget: 8,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  s.toolCallCount = 8;
  s.budget = 8;
  let d = Guard.evaluateGuards(s, {
    tool: "grep",
    args: Primitive_option.some(grepArgsDict("x", ""))
  }, p);
  assertionIsFalse("budget exhausted", d.allow);
  assertionEqual("iteration_cap", d.guard, "iteration_cap");
});

Test.test("evaluateGuards: toolCallCount < budget => not budget-denied", () => {
  let p = Guard.makePolicyWithDefaults({
    budget: 8,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  s.toolCallCount = 7;
  s.budget = 8;
  let d = Guard.evaluateGuards(s, {
    tool: "grep",
    args: Primitive_option.some(grepArgsDict("x", ""))
  }, p);
  assertionIsTrue("under budget", !(d.guard == null));
});

Test.test("evaluateGuards: same read twice (sameOpRetryCap=1) => redundant_read denied", () => {
  let p = Guard.makePolicyWithDefaults({
    sameOpRetryCap: 1,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  let call_args = Primitive_option.some(grepArgsDict("foo", "src"));
  let call = {
    tool: "grep",
    args: call_args
  };
  Guard.updateState(s, call, {
    ok: false
  }, p);
  let d = Guard.evaluateGuards(s, call, p);
  assertionIsFalse("redundant read", d.allow);
  assertionEqual("redundant_read", d.guard, "redundant_read");
});

Test.test("evaluateGuards: different read => allow", () => {
  let p = Guard.makePolicyWithDefaults({
    sameOpRetryCap: 1,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  let call1_args = Primitive_option.some(grepArgsDict("foo", "src"));
  let call1 = {
    tool: "grep",
    args: call1_args
  };
  Guard.updateState(s, call1, {
    ok: false
  }, p);
  let call2_args = Primitive_option.some(grepArgsDict("foo", "lib"));
  let call2 = {
    tool: "grep",
    args: call2_args
  };
  let d = Guard.evaluateGuards(s, call2, p);
  assertionIsTrue("different read", d.allow);
});

Test.test("evaluateGuards: consecutiveNonProducing=readDraftCap => read_budget denied", () => {
  let p = Guard.makePolicyWithDefaults({
    readDraftCap: 3,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  s.consecutiveNonProducing = 3;
  let d = Guard.evaluateGuards(s, {
    tool: "read",
    args: Primitive_option.some(argsDict({
      filePath: "x.ts"
    }))
  }, p);
  assertionIsFalse("read budget", d.allow);
  assertionEqual("read_budget", d.guard, "read_budget");
});

Test.test("evaluateGuards: consecutiveNonProducing < readDraftCap => allow", () => {
  let p = Guard.makePolicyWithDefaults({
    readDraftCap: 3,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  s.consecutiveNonProducing = 2;
  let d = Guard.evaluateGuards(s, {
    tool: "read",
    args: Primitive_option.some(argsDict({
      filePath: "x.ts"
    }))
  }, p);
  assertionIsTrue("under read budget", d.allow);
});

Test.test("evaluateGuards: deliverable_first: signal set, not executed, read => deny", () => {
  let p = Guard.makePolicyWithDefaults({
    deliverableFirst: true,
    deliverableSignal: "write:out.ts"
  });
  let s = Guard.newGuardState(p);
  s.deliverableExecuted = false;
  let d = Guard.evaluateGuards(s, {
    tool: "read",
    args: Primitive_option.some(argsDict({
      filePath: "x.ts"
    }))
  }, p);
  assertionIsFalse("deliverable_first", d.allow);
  assertionEqual("deliverable_first", d.guard, "deliverable_first");
});

Test.test("evaluateGuards: deliverable_first: deliverableSignal=null => allow", () => {
  let p = Guard.makePolicyWithDefaults({
    deliverableFirst: true,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  s.deliverableExecuted = false;
  let d = Guard.evaluateGuards(s, {
    tool: "read",
    args: Primitive_option.some(argsDict({
      filePath: "x.ts"
    }))
  }, p);
  assertionIsTrue("no signal", d.allow);
});

Test.test("evaluateGuards: deliverable_first: deliverableExecuted=true => allow", () => {
  let p = Guard.makePolicyWithDefaults({
    deliverableFirst: true,
    deliverableSignal: "write:out.ts"
  });
  let s = Guard.newGuardState(p);
  s.deliverableExecuted = true;
  let d = Guard.evaluateGuards(s, {
    tool: "read",
    args: Primitive_option.some(argsDict({
      filePath: "x.ts"
    }))
  }, p);
  assertionIsTrue("already executed", d.allow);
});

Test.test("evaluateGuards: deliverable_first: mutation call is allowed", () => {
  let p = Guard.makePolicyWithDefaults({
    deliverableFirst: true,
    deliverableSignal: "write:output.json"
  });
  let s = Guard.newGuardState(p);
  s.deliverableExecuted = false;
  let d = Guard.evaluateGuards(s, {
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "output.json"
    }))
  }, p);
  assertionIsTrue("mutation allowed", d.allow);
});

Test.test("evaluateGuards: self_script + budget exhausted => anti_self_script (clause 2 before 3)", () => {
  let p = Guard.makePolicyWithDefaults({
    budget: 5,
    blockSelfScript: true,
    deliverableSignal: null,
    blockScriptWrites: Primitive_option.some(true)
  });
  let s = Guard.newGuardState(p);
  s.toolCallCount = 5;
  s.budget = 5;
  let d = Guard.evaluateGuards(s, {
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "run.sh"
    }))
  }, p);
  assertionIsFalse("self_script first", d.allow);
  assertionEqual("anti_self_script precedence", d.guard, "anti_self_script");
});

Test.test("updateState: read increments readCount, consecutiveNonProducing, seen", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  let call_args = Primitive_option.some(grepArgsDict("x", "src"));
  let call = {
    tool: "grep",
    args: call_args
  };
  Guard.updateState(s, call, {
    ok: false
  }, p);
  assertionEqual("readCount", s.readCount, 1);
  assertionEqual("consecutiveNonProducing", s.consecutiveNonProducing, 1);
  assertionEqual("toolCallCount", s.toolCallCount, 1);
  assertionIsTrue("seen has entries", Object.keys(s.seen).length !== 0);
});

Test.test("updateState: mutation resets consecutiveNonProducing, sets deliverableExecuted+ttfa on first ok", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  s.consecutiveNonProducing = 2;
  let call_args = Primitive_option.some(argsDict({
    filePath: "src/foo.txt"
  }));
  let call = {
    tool: "write",
    args: call_args
  };
  Guard.updateState(s, call, {
    ok: true
  }, p);
  assertionEqual("consecutiveNonProducing reset", s.consecutiveNonProducing, 0);
  assertionIsTrue("deliverableExecuted", s.deliverableExecuted);
  assertionNullableEqual("ttfa", s.ttfa, 1);
  assertionEqual("execCount", s.execCount, 1);
});

Test.test("updateState: mutation with ok:false does NOT set deliverableExecuted", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  let call_args = Primitive_option.some(argsDict({
    filePath: "src/foo.txt"
  }));
  let call = {
    tool: "write",
    args: call_args
  };
  Guard.updateState(s, call, {
    ok: false
  }, p);
  assertionIsFalse("not executed", s.deliverableExecuted);
  assertionIsTrue("ttfa still null", (s.ttfa == null));
});

Test.test("updateState: self_script increments selfScriptCount and consecutiveNonProducing", () => {
  let p = Guard.makePolicyWithDefaults({
    blockScriptWrites: Primitive_option.some(true)
  });
  let s = Guard.newGuardState(p);
  Guard.updateState(s, {
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "run.sh"
    }))
  }, {
    ok: false
  }, p);
  assertionEqual("selfScriptCount", s.selfScriptCount, 1);
  assertionEqual("consecutiveNonProducing", s.consecutiveNonProducing, 1);
  assertionEqual("toolCallCount", s.toolCallCount, 1);
});

Test.test("updateState: finish no-ops (toolCallCount unchanged)", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  s.toolCallCount = 3;
  Guard.updateState(s, {
    tool: "finish"
  }, {
    ok: true
  }, p);
  assertionEqual("toolCallCount unchanged", s.toolCallCount, 3);
  assertionEqual("readCount", s.readCount, 0);
  assertionEqual("execCount", s.execCount, 0);
});

Test.test("updateState: read->read->mutation resets consecutiveNonProducing to 0", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  Guard.updateState(s, {
    tool: "grep",
    args: Primitive_option.some(grepArgsDict("a", "."))
  }, {
    ok: false
  }, p);
  Guard.updateState(s, {
    tool: "grep",
    args: Primitive_option.some(grepArgsDict("b", "."))
  }, {
    ok: false
  }, p);
  assertionEqual("after 2 reads", s.consecutiveNonProducing, 2);
  Guard.updateState(s, {
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "out.txt"
    }))
  }, {
    ok: true
  }, p);
  assertionEqual("after mutation", s.consecutiveNonProducing, 0);
});

Test.test("updateState: ttfa set once (second ok mutation doesn't change it)", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  Guard.updateState(s, {
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "a.txt"
    }))
  }, {
    ok: true
  }, p);
  let firstTtfa = s.ttfa;
  Guard.updateState(s, {
    tool: "write",
    args: Primitive_option.some(argsDict({
      filePath: "b.txt"
    }))
  }, {
    ok: true
  }, p);
  assertionEqual("ttfa stable", s.ttfa, firstTtfa);
});

Test.test("updateState: 'other' tool increments consecutiveNonProducing", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  Guard.updateState(s, {
    tool: "foo"
  }, {
    ok: false
  }, p);
  assertionEqual("consecutiveNonProducing", s.consecutiveNonProducing, 1);
  assertionEqual("toolCallCount", s.toolCallCount, 1);
});

Test.test("recordBlock: increments blockedCount and sets lastBlock", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  Guard.recordBlock(s, {
    allow: false,
    guard: "iteration_cap",
    observation: null
  });
  assertionEqual("blockedCount", s.blockedCount, 1);
  assertionEqual("lastBlock", s.lastBlock, "iteration_cap");
  assertionEqual("redundantCount", s.redundantCount, 0);
});

Test.test("recordBlock: redundant_read increments redundantCount", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  Guard.recordBlock(s, {
    allow: false,
    guard: "redundant_read",
    observation: null
  });
  assertionEqual("redundantCount", s.redundantCount, 1);
  assertionEqual("blockedCount", s.blockedCount, 1);
});

Test.test("forcingMessage: signal not executed => contains 'deliverable=NOT RUN' and 'run the deliverable'", () => {
  let p = Guard.makePolicyWithDefaults({
    deliverableSignal: "write:output.ts"
  });
  let s = Guard.newGuardState(p);
  s.deliverableExecuted = false;
  s.toolCallCount = 3;
  s.consecutiveNonProducing = 2;
  let msg = Guard.forcingMessage(s, p);
  assertionIsTrue("NOT RUN", Js_string.includes("NOT RUN", msg));
  assertionIsTrue("run the deliverable", Js_string.includes("run the deliverable", msg));
  assertionIsTrue("write:output.ts", Js_string.includes("write:output.ts", msg));
  assertionIsTrue("budget 3/8", Js_string.includes("budget 3/8", msg));
  assertionIsTrue("reads_since_produce=2", Js_string.includes("reads_since_produce=2", msg));
});

Test.test("forcingMessage: signal null => 'deliverable=n/a' and 'take a producing action'", () => {
  let p = Guard.makePolicyWithDefaults({
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  let msg = Guard.forcingMessage(s, p);
  assertionIsTrue("n/a", Js_string.includes("deliverable=n/a", msg));
  assertionIsTrue("take a producing action", Js_string.includes("take a producing action", msg));
});

Test.test("forcingMessage: executed => 'deliverable=ran'", () => {
  let p = Guard.makePolicyWithDefaults({
    deliverableSignal: "write:output.ts"
  });
  let s = Guard.newGuardState(p);
  s.deliverableExecuted = true;
  let msg = Guard.forcingMessage(s, p);
  assertionIsTrue("ran", Js_string.includes("deliverable=ran", msg));
  assertionIsTrue("take a producing action", Js_string.includes("take a producing action", msg));
});

Test.test("trajectoryMetrics: returns correct snake_case keys", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  s.readCount = 4;
  s.execCount = 2;
  s.ttfa = 3;
  s.toolCallCount = 6;
  let m = Guard.trajectoryMetrics(s);
  let ttfaVal = m.ttfa;
  let readExecRatioVal = m.read_exec_ratio;
  let toolCallCountVal = m.tool_call_count;
  let deliverableExecutedVal = m.deliverable_executed;
  let blockedCountVal = m.blocked_count;
  let redundantCountVal = m.redundant_count;
  let consecutiveNonProducingVal = m.consecutive_non_producing;
  let selfScriptCountVal = m.self_script_count;
  assertionEqual("ttfa", 3, ttfaVal);
  assertionEqual("read_exec_ratio", 2.0, readExecRatioVal);
  assertionEqual("tool_call_count", 6, toolCallCountVal);
  assertionEqual("deliverable_executed", false, deliverableExecutedVal);
  assertionEqual("blocked_count", 0, blockedCountVal);
  assertionEqual("redundant_count", 0, redundantCountVal);
  assertionEqual("consecutive_non_producing", 0, consecutiveNonProducingVal);
  assertionEqual("self_script_count", 0, selfScriptCountVal);
});

Test.test("trajectoryMetrics: read_exec_ratio when execCount=0 => readCount", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  s.readCount = 5;
  s.execCount = 0;
  let m = Guard.trajectoryMetrics(s);
  let ratioVal = m.read_exec_ratio;
  assertionEqual("ratio with 0 exec", 5.0, ratioVal);
});

Test.test("observationOk: empty string => true", () => assertionIsTrue("empty", Guard.observationOk("")));

Test.test("observationOk: 'OK done' => true", () => assertionIsTrue("OK", Guard.observationOk("OK done")));

Test.test("observationOk: 'DENIED: ...' => false", () => assertionIsFalse("DENIED", Guard.observationOk("DENIED: not allowed")));

Test.test("observationOk: '  Error: x' with leading whitespace => false", () => assertionIsFalse("Error prefix", Guard.observationOk("  Error: something went wrong")));

Test.test("observationOk: 'Traceback ...' => false", () => assertionIsFalse("Traceback", Guard.observationOk("Traceback (most recent call last)")));

Test.test("observationOk: non-string (number) => true", () => assertionIsTrue("number", Guard.observationOk(123.0)));

Test.test("observationOk: undefined => true", () => assertionIsTrue("undefined", Guard.observationOk(null)));

Test.test("TERMINATION: model that only tries SAME read is blocked by clause 4 on 2nd call", () => {
  let p = Guard.makePolicyWithDefaults({
    budget: 20,
    readDraftCap: 10,
    sameOpRetryCap: 1,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  let call_args = Primitive_option.some(grepArgsDict("x", "src"));
  let call = {
    tool: "grep",
    args: call_args
  };
  let d1 = Guard.evaluateGuards(s, call, p);
  assertionIsTrue("first allowed", d1.allow);
  Guard.updateState(s, call, {
    ok: false
  }, p);
  let d2 = Guard.evaluateGuards(s, call, p);
  assertionIsFalse("second denied", d2.allow);
  assertionEqual("redundant_read", d2.guard, "redundant_read");
  let checkAllDenied = (_remaining, _soFar) => {
    while (true) {
      let soFar = _soFar;
      let remaining = _remaining;
      if (remaining <= 0 || !soFar) {
        return soFar;
      }
      let d = Guard.evaluateGuards(s, call, p);
      _soFar = soFar && !d.allow;
      _remaining = remaining - 1 | 0;
      continue;
    };
  };
  assertionIsTrue("all denied", checkAllDenied(10, true));
});

Test.test("TERMINATION: model that only tries DIFFERENT reads is blocked by clause 5 at readDraftCap", () => {
  let p = Guard.makePolicyWithDefaults({
    budget: 30,
    readDraftCap: 3,
    sameOpRetryCap: 10,
    deliverableSignal: null
  });
  let s = Guard.newGuardState(p);
  let loop = _idx => {
    while (true) {
      let idx = _idx;
      if (idx >= p.readDraftCap) {
        return;
      }
      let call_args = Primitive_option.some(grepArgsDict("unique" + idx.toString(), "src"));
      let call = {
        tool: "grep",
        args: call_args
      };
      let d = Guard.evaluateGuards(s, call, p);
      assertionIsTrue("allowed at i=" + idx.toString(), d.allow);
      Guard.updateState(s, call, {
        ok: false
      }, p);
      _idx = idx + 1 | 0;
      continue;
    };
  };
  loop(0);
  let after_args = Primitive_option.some(grepArgsDict("new", "src"));
  let after = {
    tool: "grep",
    args: after_args
  };
  let d = Guard.evaluateGuards(s, after, p);
  assertionIsFalse("read_budget triggered", d.allow);
  assertionEqual("read_budget guard", d.guard, "read_budget");
});

Test.test("isSelfScript: deliverablePath matches unquoted string target (TS parity)", () => {
  let p = Guard.makePolicyWithDeliverablePath("/src/app.ts");
  let args = Js_dict.fromArray([[
      "filePath",
      "/src/app.ts"
    ]]);
  let call_args = Primitive_option.some(args);
  let call = {
    tool: "write",
    args: call_args
  };
  assertionIsFalse("deliverablePath match", Guard.isSelfScript(call, p));
});

Test.test("trajectoryMetrics: ttfa=null when no producing action (TS parity)", () => {
  let p = Guard.makePolicyDefault();
  let s = Guard.newGuardState(p);
  let m = Guard.trajectoryMetrics(s);
  let ttfaRaw = m.ttfa;
  assertionIsTrue("ttfa is null", (ttfaRaw == null));
});

export {
  assertionEqual,
  assertionTrue,
  assertionFalse,
  assertionIsTrue,
  assertionIsFalse,
  assertionNullableEqual,
  argsDict,
  commandDict,
  grepArgsDict,
}
/*  Not a pure module */
