// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let _FINISH_TOOLS = Js_dict.fromArray([
  [
    "finish",
    true
  ],
  [
    "return",
    true
  ],
  [
    "task_complete",
    true
  ]
]);

let _READ_ONLY_TOOLS = Js_dict.fromArray([
  [
    "grep",
    true
  ],
  [
    "read",
    true
  ],
  [
    "glob",
    true
  ],
  [
    "ls",
    true
  ]
]);

let _MUTATION_TOOLS = Js_dict.fromArray([
  [
    "write",
    true
  ],
  [
    "edit",
    true
  ],
  [
    "patch",
    true
  ],
  [
    "bash",
    true
  ],
  [
    "multiedit",
    true
  ]
]);

let _WRITE_TOOLS = Js_dict.fromArray([
  [
    "write",
    true
  ],
  [
    "edit",
    true
  ],
  [
    "patch",
    true
  ],
  [
    "multiedit",
    true
  ]
]);

function makePolicyDefault() {
  return {
    budget: 25,
    readDraftCap: 3,
    sameOpRetryCap: 1,
    blockSelfScript: true,
    deliverableFirst: true,
    deliverableSignal: null,
    deliverablePath: null,
    deliverableIsScript: null,
    blockScriptWrites: null
  };
}

function makePolicyWithDefaults(partial) {
  let defaults = makePolicyDefault();
  let v = partial.budget;
  let v$1 = partial.readDraftCap;
  let v$2 = partial.sameOpRetryCap;
  let v$3 = partial.blockSelfScript;
  let v$4 = partial.deliverableFirst;
  let v$5 = partial.deliverableSignal;
  let v$6 = partial.blockScriptWrites;
  return {
    budget: v !== undefined ? v : defaults.budget,
    readDraftCap: v$1 !== undefined ? v$1 : defaults.readDraftCap,
    sameOpRetryCap: v$2 !== undefined ? v$2 : defaults.sameOpRetryCap,
    blockSelfScript: v$3 !== undefined ? v$3 : defaults.blockSelfScript,
    deliverableFirst: v$4 !== undefined ? v$4 : defaults.deliverableFirst,
    deliverableSignal: v$5 !== undefined ? Primitive_option.valFromOption(v$5) : defaults.deliverableSignal,
    deliverablePath: defaults.deliverablePath,
    deliverableIsScript: defaults.deliverableIsScript,
    blockScriptWrites: v$6 !== undefined ? Primitive_option.valFromOption(v$6) : defaults.blockScriptWrites
  };
}

function makePolicyWithBlockScriptWrites(enabled) {
  let defaults = makePolicyDefault();
  return {
    budget: defaults.budget,
    readDraftCap: defaults.readDraftCap,
    sameOpRetryCap: defaults.sameOpRetryCap,
    blockSelfScript: defaults.blockSelfScript,
    deliverableFirst: defaults.deliverableFirst,
    deliverableSignal: defaults.deliverableSignal,
    deliverablePath: defaults.deliverablePath,
    deliverableIsScript: defaults.deliverableIsScript,
    blockScriptWrites: enabled
  };
}

function makePolicyWithDeliverablePath(path) {
  let defaults = makePolicyDefault();
  return {
    budget: defaults.budget,
    readDraftCap: defaults.readDraftCap,
    sameOpRetryCap: defaults.sameOpRetryCap,
    blockSelfScript: defaults.blockSelfScript,
    deliverableFirst: defaults.deliverableFirst,
    deliverableSignal: defaults.deliverableSignal,
    deliverablePath: path,
    deliverableIsScript: defaults.deliverableIsScript,
    blockScriptWrites: defaults.blockScriptWrites
  };
}

function makePolicyWithDeliverablePathAndBlockScript(path, enabled) {
  let defaults = makePolicyDefault();
  return {
    budget: defaults.budget,
    readDraftCap: defaults.readDraftCap,
    sameOpRetryCap: defaults.sameOpRetryCap,
    blockSelfScript: defaults.blockSelfScript,
    deliverableFirst: defaults.deliverableFirst,
    deliverableSignal: defaults.deliverableSignal,
    deliverablePath: path,
    deliverableIsScript: defaults.deliverableIsScript,
    blockScriptWrites: enabled
  };
}

function makePolicyWithDeliverableIsScript(enabled) {
  let defaults = makePolicyDefault();
  return {
    budget: defaults.budget,
    readDraftCap: defaults.readDraftCap,
    sameOpRetryCap: defaults.sameOpRetryCap,
    blockSelfScript: defaults.blockSelfScript,
    deliverableFirst: defaults.deliverableFirst,
    deliverableSignal: defaults.deliverableSignal,
    deliverablePath: defaults.deliverablePath,
    deliverableIsScript: enabled,
    blockScriptWrites: defaults.blockScriptWrites
  };
}

function _hasToolSet(tool, set) {
  return (tool in set);
}

function _hasScriptExt(target) {
  return (/\.(mjs|sh|py|js|ts|cjs|bash)\b/i.test(target));
}

function _hasHeredoc(cmd) {
  return (/<<-?\\s*['"]?[A-Za-z_]/.test(cmd));
}

function _hasRedirectScript(cmd) {
  return (/>\\s*\\S+\\.(mjs|sh|py|js|ts|cjs|bash)\\b/i.test(cmd));
}

function _hasInlineScript(cmd) {
  return (/\b(node|python3?|deno|bun)\s+-(e|c)\b/i.test(cmd));
}

function _hasCatWrite(cmd) {
  return (/\bcat\s+>\s*\S/.test(cmd));
}

function _hasBashC(cmd) {
  return (/\bbash\s+-c\b/i.test(cmd));
}

function _jsonToString(v) {
  return ((function(v) { return v == null ? "" : String(v); })(v));
}

function newGuardState(policy) {
  return {
    budget: policy.budget,
    toolCallCount: 0,
    readCount: 0,
    execCount: 0,
    selfScriptCount: 0,
    redundantCount: 0,
    blockedCount: 0,
    consecutiveNonProducing: 0,
    deliverableExecuted: false,
    ttfa: null,
    seen: {},
    lastBlock: null
  };
}

function _fingerprintToolCall(tool, args) {
  return ((function(tool, args) {
      var a = args ?? {};
      switch (tool) {
        case 'read': return 'read:' + (a.file_path ?? a.filePath ?? '');
        case 'grep': return 'grep:' + (a.pattern ?? '') + ':' + (a.path ?? a.glob ?? '');
        case 'glob': return 'glob:' + (a.pattern ?? '') + ':' + (a.path ?? '');
        case 'ls': return 'ls:' + (a.path ?? '');
        default: return tool + ':' + JSON.stringify(a).slice(0, 120);
      }
    })(tool, args));
}

function isSelfScript(call, policy) {
  let a = call.args;
  let args = a !== undefined ? Belt_Option.getWithDefault(Primitive_option.fromNullable(Primitive_option.valFromOption(a)), {}) : ({});
  let v = Js_dict.get(args, "filePath");
  let target;
  if (v !== undefined) {
    target = _jsonToString(v);
  } else {
    let v$1 = Js_dict.get(args, "path");
    if (v$1 !== undefined) {
      target = _jsonToString(v$1);
    } else {
      let v$2 = Js_dict.get(args, "file");
      target = v$2 !== undefined ? _jsonToString(v$2) : "";
    }
  }
  let match = policy.deliverableIsScript;
  if (!(match == null) && match) {
    return false;
  }
  let dp = policy.deliverablePath;
  if (dp == null) {
    if (call.tool === "bash" || call.tool === "shell") {
      let v$3 = Js_dict.get(args, "command");
      let cmd;
      if (v$3 !== undefined) {
        cmd = v$3;
      } else {
        let v$4 = Js_dict.get(args, "cmd");
        cmd = v$4 !== undefined ? v$4 : "";
      }
      if (cmd === "") {
        return false;
      } else if (_hasHeredoc(cmd) || _hasRedirectScript(cmd) || _hasInlineScript(cmd) || _hasCatWrite(cmd)) {
        return true;
      } else {
        return _hasBashC(cmd);
      }
    }
    if (!_hasToolSet(call.tool, _WRITE_TOOLS)) {
      return false;
    }
    let match$1 = policy.blockScriptWrites;
    if (!(match$1 == null) && match$1) {
      return _hasScriptExt(target);
    } else {
      return false;
    }
  }
  if (target === dp) {
    return false;
  }
  if (call.tool === "bash" || call.tool === "shell") {
    let v$5 = Js_dict.get(args, "command");
    let cmd$1;
    if (v$5 !== undefined) {
      cmd$1 = v$5;
    } else {
      let v$6 = Js_dict.get(args, "cmd");
      cmd$1 = v$6 !== undefined ? v$6 : "";
    }
    if (cmd$1 === "") {
      return false;
    } else if (_hasHeredoc(cmd$1) || _hasRedirectScript(cmd$1) || _hasInlineScript(cmd$1) || _hasCatWrite(cmd$1)) {
      return true;
    } else {
      return _hasBashC(cmd$1);
    }
  }
  if (!_hasToolSet(call.tool, _WRITE_TOOLS)) {
    return false;
  }
  let match$2 = policy.blockScriptWrites;
  if (!(match$2 == null) && match$2) {
    return _hasScriptExt(target);
  } else {
    return false;
  }
}

function classify(call, policy) {
  if (_hasToolSet(call.tool, _FINISH_TOOLS)) {
    return "finish";
  } else if (isSelfScript(call, policy)) {
    return "self_script";
  } else if (_hasToolSet(call.tool, _READ_ONLY_TOOLS)) {
    return "read";
  } else if (_hasToolSet(call.tool, _MUTATION_TOOLS)) {
    return "mutation";
  } else {
    return "other";
  }
}

function evaluateGuards(state, call, policy) {
  let a = call.args;
  let args = a !== undefined ? Belt_Option.getWithDefault(Primitive_option.fromNullable(Primitive_option.valFromOption(a)), {}) : ({});
  let fp = _fingerprintToolCall(call.tool, args);
  let kind = classify(call, policy);
  let effectiveKind = kind === "self_script" ? (
      policy.blockSelfScript === false ? "mutation" : "self_script"
    ) : kind;
  if (effectiveKind === "finish") {
    return {
      allow: true,
      guard: null,
      observation: null
    };
  }
  if (effectiveKind === "self_script") {
    return {
      allow: false,
      guard: "anti_self_script",
      observation: "DENIED: do not author or run a throwaway script. Do the task directly — write/edit the real target file, or run the actual build/test command."
    };
  }
  if (state.toolCallCount >= state.budget) {
    return {
      allow: false,
      guard: "iteration_cap",
      observation: "DENIED: tool-call budget " + String(state.budget) + " exhausted. Stop now and emit your final answer with what you have."
    };
  }
  if (effectiveKind === "read") {
    let c = Js_dict.get(state.seen, fp);
    let seenCount = c !== undefined ? c : 0;
    if (seenCount >= policy.sameOpRetryCap) {
      return {
        allow: false,
        guard: "redundant_read",
        observation: "DENIED: you already ran this exact read (" + fp + "). Reuse the result you already have; take a producing action or finish."
      };
    }
    if (state.consecutiveNonProducing >= policy.readDraftCap) {
      return {
        allow: false,
        guard: "read_budget",
        observation: "DENIED: read/draft budget exhausted (" + String(policy.readDraftCap) + " consecutive non-producing actions). Take a producing action now (write/edit) or finish."
      };
    }
    if (policy.deliverableFirst === false || (policy.deliverableSignal == null) || state.deliverableExecuted !== false || effectiveKind !== "read" && effectiveKind !== "other") {
      return {
        allow: true,
        guard: null,
        observation: null
      };
    }
    let s = policy.deliverableSignal;
    return {
      allow: false,
      guard: "deliverable_first",
      observation: "DENIED: you have not produced the deliverable yet. Your next action must be the deliverable (" + (
        (s == null) ? "" : s
      ) + ") before further exploration."
    };
  }
  if (policy.deliverableFirst === false || (policy.deliverableSignal == null) || state.deliverableExecuted !== false || effectiveKind !== "read" && effectiveKind !== "other") {
    return {
      allow: true,
      guard: null,
      observation: null
    };
  }
  let s$1 = policy.deliverableSignal;
  return {
    allow: false,
    guard: "deliverable_first",
    observation: "DENIED: you have not produced the deliverable yet. Your next action must be the deliverable (" + (
      (s$1 == null) ? "" : s$1
    ) + ") before further exploration."
  };
}

function updateState(state, call, opts, policy) {
  let kind = classify(call, policy);
  if (kind === "finish") {
    return state;
  }
  state.toolCallCount = state.toolCallCount + 1 | 0;
  let a = call.args;
  let args = a !== undefined ? Belt_Option.getWithDefault(Primitive_option.fromNullable(Primitive_option.valFromOption(a)), {}) : ({});
  let fp = _fingerprintToolCall(call.tool, args);
  if (kind === "mutation") {
    state.execCount = state.execCount + 1 | 0;
    state.consecutiveNonProducing = 0;
    if (opts.ok && !state.deliverableExecuted) {
      state.deliverableExecuted = true;
      state.ttfa = state.toolCallCount;
    }
    return state;
  }
  if (kind === "other" || kind === "finish") {
    state.consecutiveNonProducing = state.consecutiveNonProducing + 1 | 0;
    return state;
  }
  if (kind === "self_script") {
    state.selfScriptCount = state.selfScriptCount + 1 | 0;
    state.consecutiveNonProducing = state.consecutiveNonProducing + 1 | 0;
    return state;
  }
  state.readCount = state.readCount + 1 | 0;
  state.consecutiveNonProducing = state.consecutiveNonProducing + 1 | 0;
  let c = Js_dict.get(state.seen, fp);
  let existing = c !== undefined ? c : 0;
  state.seen[fp] = existing + 1 | 0;
  return state;
}

function recordBlock(state, decision) {
  state.lastBlock = decision.guard;
  state.blockedCount = state.blockedCount + 1 | 0;
  let match = decision.guard;
  if (!(match == null) && match === "redundant_read") {
    state.redundantCount = state.redundantCount + 1 | 0;
  }
  return state;
}

function forcingMessage(state, policy) {
  let match = policy.deliverableSignal;
  let deliverable = (match == null) ? "n/a" : (
      state.deliverableExecuted ? "ran" : "NOT RUN"
    );
  let sig = policy.deliverableSignal;
  let next = !(sig == null) && !state.deliverableExecuted ? "run the deliverable (" + sig + ")" : "take a producing action (write/edit) or emit your final answer";
  return "[budget " + String(state.toolCallCount) + "/" + String(state.budget) + " | deliverable=" + deliverable + " | reads_since_produce=" + String(state.consecutiveNonProducing) + "] NEXT: " + next;
}

function trajectoryMetrics(state) {
  let ratio = state.execCount === 0 ? state.readCount : state.readCount / state.execCount;
  return ((function() { return arguments[0]; }))({
    ttfa: state.ttfa,
    read_exec_ratio: ratio,
    self_script_count: state.selfScriptCount,
    tool_call_count: state.toolCallCount,
    deliverable_executed: state.deliverableExecuted,
    blocked_count: state.blockedCount,
    redundant_count: state.redundantCount,
    consecutive_non_producing: state.consecutiveNonProducing
  });
}

function observationOk(output) {
  return ((function(output) {
      var s = typeof output === 'string' ? output.trimStart() : '';
      if (s.length === 0) return true;
      var prefixes = ["DENIED", "BLOCKED", "Error", "error:", "ERROR", "Exception", "Traceback", "FAIL", "failed:"];
      for (var i = 0; i < prefixes.length; i++) {
        if (s.startsWith(prefixes[i])) return false;
      }
      return true;
    })(output));
}

function buildGuardPolicy(cfg, _tier) {
  let e = cfg.enforcement;
  let gg = e !== undefined ? e.guard : undefined;
  let tmp;
  if (gg !== undefined) {
    let v = gg.budget;
    tmp = v !== undefined ? v : 25;
  } else {
    tmp = 25;
  }
  let tmp$1;
  if (gg !== undefined) {
    let v$1 = gg.readDraftCap;
    tmp$1 = v$1 !== undefined ? v$1 : 3;
  } else {
    tmp$1 = 3;
  }
  let tmp$2;
  if (gg !== undefined) {
    let v$2 = gg.sameOpRetryCap;
    tmp$2 = v$2 !== undefined ? v$2 : 1;
  } else {
    tmp$2 = 1;
  }
  let tmp$3;
  if (gg !== undefined) {
    let v$3 = gg.blockSelfScript;
    tmp$3 = v$3 !== undefined ? v$3 : true;
  } else {
    tmp$3 = true;
  }
  let tmp$4;
  if (gg !== undefined) {
    let v$4 = gg.deliverableFirst;
    tmp$4 = v$4 !== undefined ? v$4 : true;
  } else {
    tmp$4 = true;
  }
  let tmp$5;
  if (gg !== undefined) {
    let v$5 = gg.blockScriptWrites;
    tmp$5 = v$5 !== undefined ? v$5 : null;
  } else {
    tmp$5 = null;
  }
  return {
    budget: tmp,
    readDraftCap: tmp$1,
    sameOpRetryCap: tmp$2,
    blockSelfScript: tmp$3,
    deliverableFirst: tmp$4,
    deliverableSignal: null,
    deliverablePath: null,
    deliverableIsScript: null,
    blockScriptWrites: tmp$5
  };
}

function formatScorecard(state, tier) {
  let v = state.ttfa;
  let ttfaStr = (v == null) ? "n/a" : String(v);
  let tierStr = (tier == null) ? "?" : tier;
  let b = state.lastBlock;
  return "[router scorecard | tier=" + tierStr + " | ttfa=" + ttfaStr + " | read:exec=" + String(state.readCount) + ":" + String(state.execCount) + " | self_scripts=" + String(state.selfScriptCount) + " | tool_calls=" + String(state.toolCallCount) + " | blocks=" + String(state.blockedCount) + " | stop=" + (
    (b == null) ? "none" : b
  ) + "]";
}

function _resolveEnforcementMode(params) {
  return ((function(params) {
      var enf = params.config && params.config.enforcement;
      var gateName = enf && enf.envGate != null ? enf.envGate : 'MODEL_ROUTER_ENFORCE';
      var raw = params.env && params.env[gateName];
      if (raw === '1') return { mode: 'enforced', warning: null };
      if (raw === '0') return { mode: 'off', warning: null };
      var warning = null;
      if (raw !== undefined && raw !== null && raw !== '') {
        warning = gateName + '="' + raw + '" is not "1" or "0"; ignoring env gate and using config.';
      }
      var base = (enf && enf.mode) || 'advisory';
      if (params.tier !== undefined && enf && enf.perTier && enf.perTier[params.tier] !== undefined) {
        base = enf.perTier[params.tier];
      }
      return { mode: base, warning: warning };
    })(params));
}

function _scrubText(input) {
  return ((function(input) {
      if (typeof input !== 'string' || input.length === 0) return input;
      var KEYVALUE_RE = /(\\b(?:api[_-]?key|apikey|secret|token|password|passwd|pwd|authorization)\\b\\s*[:=]\\s*)['"]?[A-Za-z0-9._-]{6,}['"]?/gi;
      var TOKEN_PATTERNS = [
        /\\bsk-ant-[A-Za-z0-9_-]{16,}/g,
        /\\bsk-[A-Za-z0-9_-]{20,}/g,
        /\\bgh[posru]_[A-Za-z0-9]{20,}/g,
        /\\bAKIA[0-9A-Z]{16}\\b/g,
        /\\bAIza[0-9A-Za-z_-]{20,}/g,
        /\\bxox[baprs]-[A-Za-z0-9-]{10,}/g,
        /\\beyJ[A-Za-z0-9._-]{20,}/g,
        /\\bBearer\\s+[A-Za-z0-9._-]+/gi,
      ];
      var out = input.replace(KEYVALUE_RE, '$1[REDACTED]');
      for (var i = 0; i < TOKEN_PATTERNS.length; i++) {
        out = out.replace(TOKEN_PATTERNS[i], '[REDACTED]');
      }
      return out;
    })(input));
}

function guardBeforeCall(params) {
  let tierStr = params.tier;
  let modeResult = _resolveEnforcementMode({
    config: params.cfg,
    tier: (tierStr == null) ? undefined : Primitive_option.some(tierStr),
    env: params.env
  });
  let mode = modeResult.mode;
  let effectiveMode;
  if (mode === "enforced") {
    let match = params.trivial;
    if ((match == null) || !match) {
      effectiveMode = "enforced";
    } else {
      let e = params.cfg.enforcement;
      if (e !== undefined) {
        let p = e.proportional;
        if (p !== undefined) {
          let match$1 = p.trivialBypass;
          effectiveMode = match$1 !== undefined && !match$1 ? "enforced" : "advisory";
        } else {
          effectiveMode = "advisory";
        }
      } else {
        effectiveMode = "advisory";
      }
    }
  } else {
    effectiveMode = mode;
  }
  if (effectiveMode === "off") {
    return {
      block: false,
      message: null,
      mode: "off",
      guard: null
    };
  }
  let policy = buildGuardPolicy(params.cfg, params.tier);
  let state = params.store.ensure(params.sessionID, policy);
  let call_tool = params.tool;
  let call_args = Primitive_option.some(params.toolArgs);
  let call = {
    tool: call_tool,
    args: call_args
  };
  let decision = evaluateGuards(state, call, policy);
  if (decision.allow) {
    return {
      block: false,
      message: null,
      mode: effectiveMode,
      guard: null
    };
  }
  if (effectiveMode === "enforced") {
    updateState(state, call, {
      ok: false
    }, policy);
    recordBlock(state, decision);
    let o = decision.observation;
    let msg = _scrubText((
      (o == null) ? "" : o
    ) + "\n" + forcingMessage(state, policy));
    return {
      block: true,
      message: msg,
      mode: effectiveMode,
      guard: decision.guard
    };
  }
  recordBlock(state, decision);
  let g = decision.guard;
  let note = _scrubText("[⚠ GUARD:" + (
    (g == null) ? "" : g
  ) + "] " + forcingMessage(state, policy));
  params.store.setPendingNote(params.sessionID, note);
  return {
    block: false,
    message: null,
    mode: effectiveMode,
    guard: decision.guard
  };
}

function guardAfterCall(params) {
  let state = params.store.get(params.sessionID);
  if (state == null) {
    return;
  }
  let policy = buildGuardPolicy(params.cfg, params.tier);
  let call_tool = params.tool;
  let call_args = Primitive_option.some(params.toolArgs);
  let call = {
    tool: call_tool,
    args: call_args
  };
  let o = params.output.output;
  let okResult = observationOk((o == null) ? null : o);
  updateState(state, call, {
    ok: okResult
  }, policy);
  let note = params.store.takePendingNote(params.sessionID);
  if (note == null) {
    return;
  }
  let match = params.output.output;
  let existing = (match == null) || typeof match !== "string" ? undefined : match;
  if (existing !== undefined) {
    params.output.output = existing + "\n\n" + note;
  } else {
    params.output.output = note;
  }
}

let defaultGuardBudget = 25;

export {
  defaultGuardBudget,
  newGuardState,
  updateState,
  recordBlock,
  isSelfScript,
  classify,
  evaluateGuards,
  forcingMessage,
  trajectoryMetrics,
  observationOk,
  buildGuardPolicy,
  formatScorecard,
  guardBeforeCall,
  guardAfterCall,
  makePolicyDefault,
  makePolicyWithDefaults,
  makePolicyWithBlockScriptWrites,
  makePolicyWithDeliverablePath,
  makePolicyWithDeliverablePathAndBlockScript,
  makePolicyWithDeliverableIsScript,
}
/* _FINISH_TOOLS Not a pure module */
